library(R6)
library(xml2)

source("xml_find_or_create_first.R")

RumbaIISWebConfig <- R6Class("RumbaIISWebConfig", list(

  app = NULL,
  subDirPath = NULL,
  webConfigPath = NULL,
  rewriteRuleName = NULL,
  rewriteRuleXPath = NULL,
  
  rumbaRewriteRulePrefix = "Rumba Rule ",
  rumbaAutodeleteMarkerComment = "Generated by Rumba. (Remove this to prevent autodeletion.)",


  initialize = function(app){

    self$app <- app

    self$subDirPath <- paste0(rumba_options$iisSitePath, "/", app$options$webPath)

    self$webConfigPath <- paste0(self$subDirPath, "/web.config")

    self$rewriteRuleName <- paste0(self$rumbaRewriteRulePrefix, app$options$basePort, "-", app$options$workerCount)

    self$rewriteRuleXPath <- paste0("/configuration/system.webServer/rewrite/rules/rule[@name='", self$rewriteRuleName, "']") 

  },

  setup = function(){

    if(!file.exists(self$subDirPath)){
      dir.create(self$subDirPath, recursive = FALSE)
    }

    self$insertOrUpdateAuthorizationWithUsersAndGroups(
      rumba_authz_controller$adUsersAndGroupsForApp(self$app))

    self$insertOrUpdateRewriteRule()

  },

  teardown = function(){

    if(any(xml_text(xml_contents(self$webConfigDoc())) == self$rumbaAutodeleteMarkerComment)){
      file.remove(self$webConfigPath)

      if(length(list.files(self$subDirPath, all.files = TRUE, no.. = TRUE)) == 0){
        file.remove(self$subDirPath)
      }

      return(TRUE)
    }

    self$removeRewriteRule()
    self$removeAuthorizationIfAppropriate()

  },

  webConfigDoc = function(){

    if(file.exists(self$webConfigPath)){
      return(read_xml(self$webConfigPath))
    }else{
      new_root <- xml_new_root("configuration")
      auto_remove_comment <- xml_comment(self$rumbaAutodeleteMarkerComment)
      xml_add_child(new_root, auto_remove_comment)
      return(new_root)
    }
  },

  rewriteRuleDoc = function(){

    doc <- xml_new_root("rule", name=self$rewriteRuleName, stopProcessing="true")

    xml_add_child(doc, "match", url=paste0("^(.*)"))
    xml_add_child(doc, "conditions", logicalGrouping="MatchAll", trackAllCaptures="false")

    webFarmName <- rumba_iis_application_host_config$webFarmNameForRumbaApp(self$app)

    xml_add_child(doc, "action", type="Rewrite", url=paste0("http://",webFarmName ,"/{R:1}"))

    return(doc)
  },

  rewriteRuleExists = function(){
    doc <- self$webConfigDoc()
    xPath <- self$rewriteRuleXPath

    nodeSet <- xml_find_all(doc, xPath)

    if(length(nodeSet) == 1){
      return(TRUE)
    }

    if(length(nodeSet) == 0){
      return(FALSE)
    }    

    stop(paste0("Multiple rewrite rule entries found for ", self$self$rewriteRuleName))
  },

  removeRewriteRule = function(){

    if(!self$rewriteRuleExists()){
      return(FALSE)
    }

    doc <- self$webConfigDoc()
    xPath <- self$rewriteRuleXPath

    nodeSet <- xml_find_all(doc, xPath)

    xml_remove(nodeSet)

    write_xml(doc, self$webConfigPath)

    return(TRUE)
  },

  insertOrUpdateRewriteRule = function(){ 

    doc <- self$webConfigDoc()

    # Clear any existing entries for this app
    xPath <- self$rewriteRuleXPath
    nodeSet <- xml_find_all(doc, xPath)
    xml_remove(nodeSet)

    rewriteRules <- xml_find_or_create_first(doc, "//configuration/system.webServer/rewrite/rules")

    rewriteRules <- rewriteRules

    newRule <- self$rewriteRuleDoc()

    xml_add_child(rewriteRules, newRule)

    write_xml(doc, self$webConfigPath)

    return(TRUE)
  },

  #
  # Authorization
  #

  insertOrUpdateAuthorizationWithUsersAndGroups = function(usersAndGroups){
    if(is.null(usersAndGroups)){
      return(TRUE)
    }

    doc <- self$webConfigDoc()

    nodeSet <- xml_find_all(doc, "//configuration/system.webServer/security/authorization/*")
    xml_remove(nodeSet)

    authz <- xml_find_or_create_first(doc, "//configuration/system.webServer/security/authorization")

    xml_add_child(authz, "clear")

    userList <- usersAndGroups %>% 
      filter(objectType == "user") %>% 
      pull("sAMAccountName") %>%
      paste(collapse=",")



    xml_add_child(authz, "add", accessType = "allow", users=userList)

    groupList <- usersAndGroups %>% 
      filter(objectType == "group") %>% 
      pull("sAMAccountName") %>%
      walk(function(x){xml_add_child(authz, "add", accessType = "allow", roles=x)})


    write_xml(doc, self$webConfigPath)

    return(TRUE)
  },

  removeAuthorizationIfAppropriate = function(){
    if(is.null(self$app$options$allow)){
      return(TRUE)
    }

    doc <- self$webConfigDoc()

    nodeSet <- xml_find_all(doc, "//configuration/system.webServer/security/authorization")
    xml_remove(nodeSet)

    write_xml(doc, self$webConfigPath)

  }


))